objects/Chart__c.object
<CustomObject>
    <fields>
        <fullName>Dashboard_Data__c</fullName>
        <description>Dashboard Data</description>
        <inlineHelpText>Dashboard Data</inlineHelpText>
        <label>Dashboard Data</label>
        <referenceTo>Dashboard_Data__c</referenceTo>
        <relationshipLabel>Charts</relationshipLabel>
        <relationshipName>Charts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chart</label>
    <nameField>
        <label>Chart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dashboard_Data__c.object
<CustomObject>
    <fields>
        <fullName>Code_Changes_Issues_Ratio__c</fullName>
        <description>Code Changes Issues Ratio</description>
        <inlineHelpText>Code Changes Issues Ratio</inlineHelpText>
        <label>Code Changes Issues Ratio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customization_Ratio__c</fullName>
        <description>Customization Ratio</description>
        <inlineHelpText>Customization Ratio</inlineHelpText>
        <label>Customization Ratio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <description>Environment</description>
        <inlineHelpText>Environment</inlineHelpText>
        <label>Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance_Description__c</fullName>
        <description>Instance Description</description>
        <inlineHelpText>Instance Description</inlineHelpText>
        <label>Instance Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Edition__c</fullName>
        <description>Org Edition</description>
        <inlineHelpText>Org Edition</inlineHelpText>
        <label>Org Edition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <description>Org Id</description>
        <inlineHelpText>Org Id</inlineHelpText>
        <label>Org Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_URL__c</fullName>
        <description>Org URL</description>
        <inlineHelpText>Org URL</inlineHelpText>
        <label>Org URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QoC_Variation__c</fullName>
        <description>QoC Variation</description>
        <inlineHelpText>QoC Variation</inlineHelpText>
        <label>QoC Variation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QoC__c</fullName>
        <description>QoC</description>
        <inlineHelpText>QoC</inlineHelpText>
        <label>QoC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scan_Date__c</fullName>
        <description>Scan Date</description>
        <inlineHelpText>Scan Date</inlineHelpText>
        <label>Scan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scan_ID_External__c</fullName>
        <description>Scan ID External</description>
        <inlineHelpText>Scan ID External</inlineHelpText>
        <label>Scan ID External</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Debt_Variation__c</fullName>
        <description>Technical Debt Variation</description>
        <inlineHelpText>Technical Debt Variation</inlineHelpText>
        <label>Technical Debt Variation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Technical_Debt__c</fullName>
        <description>Technical Debt</description>
        <inlineHelpText>Technical Debt</inlineHelpText>
        <label>Technical Debt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Issues_Variation__c</fullName>
        <description>Total Issues Variation</description>
        <inlineHelpText>Total Issues Variation</inlineHelpText>
        <label>Total Issues Variation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Issues__c</fullName>
        <description>Total Issues</description>
        <inlineHelpText>Total Issues</inlineHelpText>
        <label>Total Issues</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dashboard Data</label>
    <nameField>
        <label>Dashboard Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboard Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dataset__c.object
<CustomObject>
    <fields>
        <fullName>Chart__c</fullName>
        <description>Chart</description>
        <inlineHelpText>Chart</inlineHelpText>
        <label>Chart</label>
        <referenceTo>Chart__c</referenceTo>
        <relationshipLabel>Datasets</relationshipLabel>
        <relationshipName>Datasets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Label__c</fullName>
        <description>Group Label</description>
        <inlineHelpText>Group Label</inlineHelpText>
        <label>Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Label</description>
        <inlineHelpText>Label</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value</description>
        <inlineHelpText>Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dataset</label>
    <nameField>
        <label>Dataset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Inst_Org_Id__c</fullName>
        <description>Id of the org that is connected to current instance</description>
        <inlineHelpText>Id of the org that is connected to current instance</inlineHelpText>
        <label>Instance Org Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DashboardController.cls
public with sharing class DashboardController {
    
    private final static String MSG_UPDATED_OK = ' Data updated successfully.';
    private final static String MSG_INVAL_TOKEN = 'No valid token detected. On "Quality Clouds" tab, click "Go To Settings" button and click "Get Token" or "Refresh Token" to get valid token.';
    private final static String MSG_ORG_NOT_CONNECTED = 'Current org is not connected to Quality Clouds service. To be able to scan current org for issues please go to "Quality Clouds" tab. On "Instances" page, click "Connect org to QC" button.';
    private final static String MSG_MORE_THAN_ONE_INST = 'More than 1 instance with current org ID found. Please remove unnecessary instances and try again.';
    public String msgInvalidToken { get; private set; }
    public String msgOrgIsNotConnected { get; private set; }
    private final static Integer ITEMS_TO_SHOW = 10;
    private DataWrapper data; 
    private DatasetcWrapper[] dwList;
    public String message_type_out{get;set;}
    public String message_out{get;set;}
    public String message{get;set;}
    public String message_type{get;set;}

    public DashboardController() {
        msgInvalidToken = MSG_INVAL_TOKEN;
        msgOrgIsNotConnected = MSG_ORG_NOT_CONNECTED;
        message = ApexPages.currentPage().getParameters().get('message');
        message_type = ApexPages.currentPage().getParameters().get('message_type');
    }

    private class DatasetcWrapper implements Comparable {
        private Dataset__c d;
        public DatasetcWrapper(Dataset__c d) {
            this.d = d;
        }
        public Dataset__c getDatasetc (){
            return this.d;
        }
        public Integer compareTo(Object compareTo) {
            DatasetcWrapper ctD = (DatasetcWrapper) compareTo;
            if (ctD.d.Label__c < this.d.Label__c) {
                return +1;
            }
            if (ctD.d.Label__c > this.d.Label__c) {
                return -1;
            }
            return 0; 
        }   
    }    
    
    public class DataWrapper{
        public Dashboard_Data__c numbers {get;set;}
        public List<DataSet> evolutionOfIssuesData{get;set;}
        public DataSet issuesBySeverityData{get;set;}
        public List<DataSet> issuesByImpactAreaData{get;set;}
        public DataSet issuesDataPrivacyData{get;set;}
        public DataSet issuesByBestPracticesData{get;set;}
        public DataSet configurationElementsData{get;set;}
    }
    
    public class DataSet{
        public String lables{get;set;}
        public String groupLables{get;set;}
        public List<Decimal> values{get;set;}
    }
    
    private List<Dataset__c> sortDatasetcListByLabel(List<Dataset__c> dList) {
        dwList = new List<DatasetcWrapper>();
        for (Dataset__c d: dList){
            dwList.add(new DatasetcWrapper(d));
        }
        dwList.sort();
        List<Dataset__c> sortedList = new  List<Dataset__c>();
        for (DatasetcWrapper dw: dwList){
            sortedList.add(dw.getDatasetc());
        }
        return sortedList;
    }
  
    public DataWrapper getData(){
        
        if (!getCheckIfTokenValid()) {
            return null;
        }
        if (data!=null){
            return data;
        } else {
            data = new DataWrapper ();
            
            List <Dashboard_Data__c> dataNumbers = [SELECT 
                                                    Id, 
                                                    CreatedDate,
                                                    Total_Issues__c, 
                                                    Total_Issues_Variation__c, 
                                                    Technical_Debt__c, 
                                                    Technical_Debt_Variation__c, 
                                                    Customization_Ratio__c, 
                                                    Code_Changes_Issues_Ratio__c, 
                                                    QoC__c, 
                                                    QoC_Variation__c, 
                                                    Scan_Date__c, 
                                                    Scan_ID_External__c, 
                                                    Instance_Description__c, 
                                                    Environment__c, 
                                                    Org_URL__c, 
                                                    Org_Edition__c, 
                                                    Org_Id__c
                                                    FROM Dashboard_Data__c
                                                    ORDER BY CreatedDate DESC
                                                    LIMIT 1
                                                   ];
            if (!dataNumbers.isEmpty()) {
                data.numbers = dataNumbers[0];
            }                 
            if (data.numbers?.Id != null){
                for (Chart__c chart: [SELECT Name, 
                                            Dashboard_Data__c,
                                            (SELECT Group_Label__c, Label__c, Value__c FROM Datasets__r 
                                                ORDER BY Value__c 
                                                DESC NULLS LAST) 
                                      FROM Chart__c 
                                      WHERE Dashboard_Data__c =: data.numbers.Id])
                {
                    addChartToData (chart);                   
                }
            }           
            return data;
        }
    }

    private void addChartToData (Chart__c chart){
        if (chart.Name == DashboardControllerHelper.CHART_NAME_IBP){
            data.issuesByBestPracticesData = chartToDataset(chart, null, ITEMS_TO_SHOW);
        } else if (chart.Name == DashboardControllerHelper.CHART_NAME_EOI){
            data.evolutionOfIssuesData = new List<DataSet>();
            data.evolutionOfIssuesData.add(chartToDataset(chart, DashboardControllerHelper.GROUP_LABEL_ISSUES, 0));
            data.evolutionOfIssuesData.add(chartToDataset(chart, DashboardControllerHelper.GROUP_LABEL_TECH_DEBT, 0));
        } else if (chart.Name == DashboardControllerHelper.CHART_NAME_IIA){
            data.issuesByImpactAreaData = new List<DataSet>();
            data.issuesByImpactAreaData.add(chartToDataset(chart, null, 0));
        } else if (chart.Name == DashboardControllerHelper.CHART_NAME_IDP){
            data.issuesDataPrivacyData = chartToDataset(chart, null, 0);
        } else if (chart.Name == DashboardControllerHelper.CHART_NAME_IBS){
            data.issuesBySeverityData = chartToDataset(chart, null, 0);
        } else if (chart.Name == DashboardControllerHelper.CHART_NAME_CE){
            data.configurationElementsData = chartToDataset(chart, null, ITEMS_TO_SHOW);
        }
    }

    private List<Dataset__c> groupExtraItems(List<Dataset__c> datasetcList, Integer itemsToShow){
        if (datasetcList.size() > itemsToShow) {
            Integer counter = 1;
            Integer otherItemsCounter = 0;
            Decimal otherItemsSum = 0;
            List<Dataset__c> tempDatasetcList = new List<Dataset__c>();
            for (Dataset__c d : datasetcList) {
                if (counter < itemsToShow) {
                    tempDatasetcList.add(d);
                } else {
                    otherItemsCounter++;
                    otherItemsSum += d.Value__c;
                }
                counter++;
            }
            if (otherItemsCounter > 0) {
                tempDatasetcList.add(new Dataset__c (
                    Group_Label__c = datasetcList[0].Group_Label__c,
                    Value__c = otherItemsSum,
                    Label__c = 'Other ' + otherItemsCounter + ' items'
                ));
            }               
            datasetcList = tempDatasetcList;
        }
        return datasetcList;
    }
    
    private DataSet chartToDataset (Chart__c chart, String groupLabel, Integer itemsToShow){
        DataSet chartDataSet  = new DataSet();
        List<String> lablesList = new List<String>();
        List<String> groupLablesList = new List<String>();
        List<Decimal> valuesList = new List<Decimal>();
        List<Dataset__c> datasetcList;
        if (groupLabel!=null) {
            datasetcList = sortDatasetcListByLabel(chart.Datasets__r);
        } else {
            datasetcList = chart.Datasets__r;
        }

        if (itemsToShow > 0) {
            datasetcList = groupExtraItems(datasetcList, itemsToShow);
        }
        for (Dataset__c dataRow : datasetcList){
            if ((groupLabel == dataRow.Group_Label__c)||(dataRow.Group_Label__c == '')){
                lablesList.add( String.escapeSingleQuotes(dataRow.Label__c));
                valuesList.add(dataRow.Value__c);
                groupLablesList.add(dataRow.Group_Label__c);
            }            
        }
        chartDataSet.lables = JSON.serialize(lablesList);
        chartDataSet.groupLables = JSON.serialize(groupLablesList);        
        chartDataSet.values = valuesList;
        return chartDataSet;
    }  
    
    public Boolean getCheckIfTokenValid (){       
        return ControllerHelperQC.checkIfTokenValid();
    }

    public Boolean getCheckIfOrgConnected(){   
        return ControllerHelperQC.checkIfOrgConnected();   
    }
    
    public PageReference updateDataFromPortal (){
        
        try {
            String currentOrgId = UserInfo.getOrganizationId();
            PermissionChecker.exceptionIfNotAccessible(Instance__c.getSObjectType());
            List<Instance__c> instancesForCurrentOrg = [SELECT Id__c, Inst_Org_Id__c FROM Instance__c WHERE Inst_Org_Id__c =: currentOrgId];            
            String instanceId;
            if (instancesForCurrentOrg.size() == 1) {
                instanceId = instancesForCurrentOrg[0].ID__c;
            } else if ( instancesForCurrentOrg.size() < 1 ){
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, MSG_ORG_NOT_CONNECTED));
                return null;
            } else {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, MSG_MORE_THAN_ONE_INST));
                return null;
            }
            DashboardControllerHelper helper = new DashboardControllerHelper();
            Datetime lastScanDate = getdata()?.numbers?.Scan_Date__c;     
            String result = helper.updateDataFromPortal(instanceId, lastScanDate);    
            if (result == 'OK') {
                message_type_out = 'confirm';
                message_out = MSG_UPDATED_OK;
                PageReference tempPage = new PageReference('/apex/Dashboard');
                tempPage.getParameters().put('message_type', message_type_out);
                tempPage.getParameters().put('message', message_out);
                tempPage.setRedirect(true);
                return tempPage;
            } else {
                ApexPages.getMessages().clear();
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, result));
                return null;
            }        
        } catch (Exception e) {    
            System.debug(LoggingLevel.Error, e.getStackTraceString());    
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getMessage() + ', ' + e.getCause()));
            return null;
        }
    }  
}