objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Org description - Set on the Quality Clouds scan site when the instance was registered</description>
        <inlineHelpText>Org description - Set on the Quality Clouds scan site when the instance was registered</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment_Type__c</fullName>
        <description>Org environment type - Set on the Quality Clouds scan site when the instance was registered</description>
        <inlineHelpText>Org environment type - Set on the Quality Clouds scan site when the instance was registered</inlineHelpText>
        <label>Environment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance_Type__c</fullName>
        <description>SaaS Platform type</description>
        <inlineHelpText>SaaS Platform type</inlineHelpText>
        <label>Instance Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Featured_Banch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Featured Banch</description>
        <inlineHelpText>Is Featured Banch</inlineHelpText>
        <label>Is Featured Banch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <description>Org URL - Detected automatically during scan. Not available for feature branch scans</description>
        <inlineHelpText>Org URL - Detected automatically during scan. Not available for feature branch scans</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/globalCallsToQCTest.cls
@isTest
class  globalCallsToQCTest {
       
    @isTest
    static void execute_scannOK() {

        upsert new Instance__c(url__c='url', Description__c='dec', Environment_Type__c='dev',ID__c= '1', Instance_Type__c='salesforcce', Is_Featured_Banch__c=true) ID__c;

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('scanok');
        mock.setStatusCode(202);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        globalCallsToQC globalCallsToQCObj = new globalCallsToQC();

        boolean testout = globalCallsToQCObj.execute_scann([SELECT url__c, Description__c, ID__c, Environment_Type__c, Instance_Type__c, Is_Featured_Banch__c, Id FROM Instance__c WHERE ID__c = '1' ORDER BY CreatedDate DESC LIMIT 1], 'develop');

        Test.stopTest();
        System.assertEquals(testout, true);
    }

}