objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QCIssue__c.object
<CustomObject>
    <description>Salesforce Issue fetched from the Quality Clouds API</description>
    <fields>
        <fullName>Created_By__c</fullName>
        <description>User Id who created the affected element</description>
        <inlineHelpText>User Id who created the affected element</inlineHelpText>
        <label>Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_On__c</fullName>
        <description>Date on which the affected element was created</description>
        <inlineHelpText>Date on which the affected element was created</inlineHelpText>
        <label>Created On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Documentation__c</fullName>
        <description>Documentation URL</description>
        <inlineHelpText>Documentation URL</inlineHelpText>
        <label>Documentation</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Element_Name__c</fullName>
        <description>Name of the affected element</description>
        <inlineHelpText>Name of the affected element</inlineHelpText>
        <label>Element Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Element_Type__c</fullName>
        <description>Type of the affected element</description>
        <inlineHelpText>Type of the affected element</inlineHelpText>
        <label>Element Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact_Area__c</fullName>
        <description>Impact Area</description>
        <inlineHelpText>Impact Area</inlineHelpText>
        <label>Impact Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SCALABILITY</fullName>
                </value>
                <value>
                    <fullName>PERFORMANCE</fullName>
                </value>
                <value>
                    <fullName>MANAGEABILITY</fullName>
                </value>
                <value>
                    <fullName>SECURITY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <description>Issue Type</description>
        <inlineHelpText>Issue Type</inlineHelpText>
        <label>Issue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>Line number where the issue was detected</description>
        <inlineHelpText>Line number where the issue was detected</inlineHelpText>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <description>Link from Quality Clouds API</description>
        <inlineHelpText>Link from Quality Clouds API</inlineHelpText>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_to_Element__c</fullName>
        <description>Go to Element</description>
        <inlineHelpText>Go to Element</inlineHelpText>
        <label>Link to Element</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Scan__c</fullName>
        <description>Scan the issue is part of</description>
        <inlineHelpText>Scan the issue is part of</inlineHelpText>
        <label>Scan</label>
        <referenceTo>Scann__c</referenceTo>
        <relationshipLabel>QCIssues</relationshipLabel>
        <relationshipName>QCIssues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Severity</description>
        <inlineHelpText>Severity</inlineHelpText>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HIGH</fullName>
                </value>
                <value>
                    <fullName>MEDIUM</fullName>
                </value>
                <value>
                    <fullName>LOW</fullName>
                </value>
                <value>
                    <fullName>WARNING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Updated_By__c</fullName>
        <description>User Id who last updated the affected element</description>
        <inlineHelpText>User Id who last updated the affected element</inlineHelpText>
        <label>Updated By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Updated_On__c</fullName>
        <description>Date on which the affected element was last updated</description>
        <inlineHelpText>Date on which the affected element was last updated</inlineHelpText>
        <label>Updated On</label>
        <type>DateTime</type>
    </fields>
    <label>QCIssue</label>
    <nameField>
        <label>QCIssue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QCIssues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Scann__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <description>Branch scanned. Only available for feature branch scans</description>
        <inlineHelpText>Branch scanned. Only available for feature branch scans</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Elements__c</fullName>
        <description>Number of Configuration Elements analysed</description>
        <inlineHelpText>Number of Configuration Elements analysed</inlineHelpText>
        <label>Configuration Elements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Scan date</description>
        <inlineHelpText>Scan date</inlineHelpText>
        <label>Scan Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration of the Scan</description>
        <inlineHelpText>Duration of the Scan</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Internal scan id. Used only for technical support</description>
        <externalId>true</externalId>
        <inlineHelpText>Internal scan id. Used only for technical support</inlineHelpText>
        <label>Internal ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <description>Instance for this scann</description>
        <inlineHelpText>Instance for this scann</inlineHelpText>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipName>Scanns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quality_of_Cloud__c</fullName>
        <description>Overall quality indicator, not available for feature branch scans</description>
        <inlineHelpText>Overall quality indicator, not available for feature branch scans</inlineHelpText>
        <label>Quality of Cloud</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scan_Type__c</fullName>
        <description>Scan Type</description>
        <inlineHelpText>Scan Type</inlineHelpText>
        <label>Scan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Result of the scan</description>
        <inlineHelpText>Result of the scan</inlineHelpText>
        <label>Scan Result</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Debt_hours__c</fullName>
        <description>Development time to fix the detected issues</description>
        <inlineHelpText>Development time to fix the detected issues</inlineHelpText>
        <label>Technical Debt (hours)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Issues__c</fullName>
        <description>Number of issues detected in the scan</description>
        <inlineHelpText>Number of issues detected in the scan</inlineHelpText>
        <label>Total Issues</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CsvDownloadController.cls
public with sharing class CsvDownloadController {
    public String input {get;set;}
    public String fileName {get;set;}
    public CsvDownloadController() {
        String id_scan = ApexPages.currentPage().getParameters().get('id');
        Scann__c scan = [SELECT Branch_Name__c, Date__c, Duration__c, ID__c, Instance__c, Scan_Type__c, Quality_of_Cloud__c, Configuration_Elements__c, State__c, Technical_Debt_hours__c, Total_Issues__c, Id  FROM Scann__c WHERE ID__c = :id_scan ORDER BY CreatedDate DESC];
        List<QCIssue__c > issuelist = [SELECT Created_By__c, Created_On__c, Element_Name__c, Link_to_Element__c, Documentation__c, Element_Type__c, ID__c, Impact_Area__c, Issue__c, Line_Number__c, Link__c, Scan__c, Severity__c, Updated_By__c, Updated_On__c, Id FROM QCIssue__c WHERE Scan__c = :scan.Id];
        string header = 'Scan Date;Affected Element SysId;Affected Element Name;Created By;Created On;Updated By;Updated On;Severity;Impact Area;Issue Type;Line Number;Best Practice Link;Configuration Element Type\n';
        input = header ;
        fileName = 'scan_'+scan.ID__c;
        for(QCIssue__c isue: issuelist)
        {

            string recordString = scan.Date__c+';'+isue.Link_to_Element__c+';'+isue.Element_Name__c+';'+isue.Created_By__c+';'+isue.Created_On__c+';'+isue.Updated_By__c+';'+isue.Updated_On__c+';'+isue.Severity__c+';'+isue.Impact_Area__c+';'+isue.Issue__c+';'+isue.Line_Number__c+';'+isue.Documentation__c+';'+isue.Element_Type__c +'\n';

            input = input +recordString;

        }
    }

}