objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Org description - Set on the Quality Clouds scan site when the instance was registered</description>
        <inlineHelpText>Org description - Set on the Quality Clouds scan site when the instance was registered</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment_Type__c</fullName>
        <description>Org environment type - Set on the Quality Clouds scan site when the instance was registered</description>
        <inlineHelpText>Org environment type - Set on the Quality Clouds scan site when the instance was registered</inlineHelpText>
        <label>Environment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance_Type__c</fullName>
        <description>SaaS Platform type</description>
        <inlineHelpText>SaaS Platform type</inlineHelpText>
        <label>Instance Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Featured_Banch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Featured Banch</description>
        <inlineHelpText>Is Featured Banch</inlineHelpText>
        <label>Is Featured Banch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <description>Org URL - Detected automatically during scan. Not available for feature branch scans</description>
        <inlineHelpText>Org URL - Detected automatically during scan. Not available for feature branch scans</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QCIssue__c.object
<CustomObject>
    <description>Salesforce Issue fetched from the Quality Clouds API</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scan__c</fullName>
        <description>Scan the issue is part of</description>
        <inlineHelpText>Scan the issue is part of</inlineHelpText>
        <label>Scan</label>
        <referenceTo>Scann__c</referenceTo>
        <relationshipLabel>QCIssues</relationshipLabel>
        <relationshipName>QCIssues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>QCIssue</label>
    <nameField>
        <label>QCIssue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QCIssues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Scann__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <description>Branch scanned. Only available for feature branch scans</description>
        <inlineHelpText>Branch scanned. Only available for feature branch scans</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Scan date</description>
        <inlineHelpText>Scan date</inlineHelpText>
        <label>Scan Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Internal scan id. Used only for technical support</description>
        <externalId>true</externalId>
        <inlineHelpText>Internal scan id. Used only for technical support</inlineHelpText>
        <label>Internal ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <description>Instance for this scann</description>
        <inlineHelpText>Instance for this scann</inlineHelpText>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipName>Scanns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scan_Type__c</fullName>
        <description>Scan Type</description>
        <inlineHelpText>Scan Type</inlineHelpText>
        <label>Scan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Result of the scan</description>
        <inlineHelpText>Result of the scan</inlineHelpText>
        <label>Scan Result</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCopadoIntegrationTriggers.cls
@isTest
private class TestCopadoIntegrationTriggers {

    private static User runningUser;
    private static copado__Environment__c sourceEnv1;
    private static copado__Environment__c targetEnv2;
    private static copado__Org__c sourceOrg1;
    private static copado__Org__c targetOrg2;


    private static void setupTestData() {
        // Create admin user for creating and assigning the Copado licenses to a running user
        User adminUser = createAdminUser();
        insert adminUser;

        System.runAs(adminUser) {
            // Create running user
            runningUser = createStandardUser();
            runningUser.ProfileId = adminUser.ProfileId;
            insert runningUser;

            // Assign the Copado permission set to the running user
            PermissionSetAssignment psa = new PermissionSetAssignment (
                PermissionSetId = getCopadoUserPermissionSet().Id,
                AssigneeId = runningUser.Id
            );
            insert psa;

            // Assign A Copado License to the running User
            copado.GlobalAPI copadoGlobalAPI = new copado.GlobalAPI();
            copado.GlobalAPI.UserLicense UL = new copado.GlobalAPI.UserLicense();
            UL.isCopadoEnabled = true;
            UL.isCCMEnabled = true;
            UL.userId = runningUser.id;
            copadoGlobalAPI.upsertCopadoLicense(runningUser.id, UL);
        }

    }

    @isTest(SeeAllData=false) static void TestNewScanPage() {
        setupTestData();
        System.runAs(runningUser) {
            copado__Git_Repository__c repo = new copado__Git_Repository__c(copado__URI__c = 'https://github.com/testgit');
            upsert repo;
            copado__Deployment_Flow__c pipe = new copado__Deployment_Flow__c(copado__Git_Repository__c = repo.Id);
            upsert pipe;
            copado__Project__c project = new copado__Project__c(copado__Deployment_Flow__c = pipe.Id);
            upsert project;
            copado__User_Story__c userStory = new copado__User_Story__c( copado__Project__c = project.Id);
            List<copado__User_Story__c> userStoryList = new List<copado__User_Story__c>();
            userStoryList.add(userStory);
            upsert userStoryList;
            userStory = [SELECT Id, copado__Project__c, Name FROM copado__User_Story__c WHERE Id = :userStory.Id Limit 1];
            Instance__c instance;
            Instance__c instancee = new Instance__c(url__c='https://github.com/testgit', Description__c='dec', Environment_Type__c='dev',ID__c= '1', Instance_Type__c='salesforcce', Is_Featured_Banch__c=true);
            upsert instance = instancee ID__c;
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('scanok');
            mock.setStatusCode(202);
            mock.setHeader('Content-Type', 'application/json');
			
            Test.startTest();
            
            Run_QualityClouds_Scan_Page_Controller.doScan(userStoryList);

            Test.stopTest();
            System.assertEquals('smoke', 'smoke');
        }
    }
    @isTest(SeeAllData=false) static void TestScanTriggers() {
        setupTestData();
        System.runAs(runningUser) {
            copado__Git_Repository__c repo = new copado__Git_Repository__c(copado__URI__c = 'https://github.com/testgit');
            upsert repo;
            copado__Deployment_Flow__c pipe = new copado__Deployment_Flow__c(copado__Git_Repository__c = repo.Id);
            upsert pipe;
            copado__Project__c project = new copado__Project__c(copado__Deployment_Flow__c = pipe.Id);
            upsert project;
            copado__User_Story__c userStory = new copado__User_Story__c( copado__Project__c = project.Id);
            upsert userStory;
            userStory = [SELECT Id, copado__Project__c, Name FROM copado__User_Story__c WHERE Id = :userStory.Id Limit 1];
            Instance__c instance;
            Instance__c instancee = new Instance__c(url__c='https://github.com/testgit', Description__c='dec', Environment_Type__c='dev',ID__c= '1', Instance_Type__c='salesforcce', Is_Featured_Banch__c=true);
            upsert instance = instancee ID__c;
            Scann__c scan = new Scann__c(ID__c= '1',Date__c = Datetime.valueOf('2019-07-23 08:25:59'), State__c='SUCCESS', Scan_Type__c='feature-branch-scan', Branch_Name__c='feature/'+userStory.Name, Instance__c= instance.Id);
            upsert scan ID__c;

            Test.startTest();
            update scan;
            Test.stopTest();
            System.assertEquals('smoke', 'smoke');
        }
    }
    @isTest(SeeAllData=false) static void TestIssueTriggers() {
        setupTestData();
        System.runAs(runningUser) {
            copado__Git_Repository__c repo = new copado__Git_Repository__c(copado__URI__c = 'https://github.com/testgit');
            upsert repo;
            copado__Deployment_Flow__c pipe = new copado__Deployment_Flow__c(copado__Git_Repository__c = repo.Id);
            upsert pipe;
            copado__Project__c project = new copado__Project__c(copado__Deployment_Flow__c = pipe.Id);
            upsert project;
            copado__User_Story__c userStory = new copado__User_Story__c( copado__Project__c = project.Id);
            upsert userStory;
            userStory = [SELECT Id, copado__Project__c, Name FROM copado__User_Story__c WHERE Id = :userStory.Id Limit 1];
            Instance__c instance;
            Instance__c instancee = new Instance__c(url__c='https://github.com/testgit', Description__c='dec', Environment_Type__c='dev',ID__c= '1', Instance_Type__c='salesforcce', Is_Featured_Banch__c=true);
            upsert instance = instancee ID__c;
            Scann__c scan = new Scann__c(ID__c= '1',Date__c = Datetime.valueOf('2019-07-23 08:25:59'), State__c='SUCCESS', Scan_Type__c='feature-branch-scan', Branch_Name__c='feature/'+userStory.Name, Instance__c= instance.Id);
            upsert scan ID__c;
            QCIssue__c issue = new QCIssue__c(Scan__c = scan.id , ID__c= '2');
            upsert issue ID__c;
            Test.startTest();
            update issue;
            Test.stopTest();
            System.assertEquals('smoke', 'smoke');
        }
    }
    public static User createAdminUser(){
        Profile adminProfile = [Select Id From Profile Where Name = 'System Administrator' Limit 1];
        User newUser = new User();
        newUser.ProfileId = adminProfile.Id;
        newUser.FirstName = 'Rebekah';
        newUser.LastName = 'Admin';
        newUser.email = 'admin@aa.test';
        newUser.Username = 'admin@aa.test';
        newUser.Alias = 'tadmin';
        newUser.CommunityNickname = 'tadmin';
        newUser.LocaleSidKey = 'es_ES';
        newUser.emailencodingkey='UTF-8';
        newUser.languagelocalekey='en_US';
        newUser.TimeZoneSidKey='Europe/Rome';
        return newUser;
    }

    public static User createStandardUser(){
        Profile standardProfile = [Select Id From Profile Where Name = 'Standard User' Limit 1];
        User newUser = new User();
        newUser.ProfileId = standardProfile.Id;
        newUser.FirstName = 'Daniel';
        newUser.LastName = 'Standard';
        newUser.email = 'standard@aa.test';
        newUser.Username = 'standard@aa.test';
        newUser.Alias = 'tandard';
        newUser.CommunityNickname = 'tstand';
        newUser.LocaleSidKey = 'es_ES';
        newUser.emailencodingkey='UTF-8';
        newUser.languagelocalekey='en_US';
        newUser.TimeZoneSidKey='Europe/Rome';

        return newUser;
    }

    public static PermissionSet getCopadoUserPermissionSet(){
        return [SELECT Id FROM PermissionSet WHERE Name = 'Copado_User'];
    }
}