objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QCIssue__c.object
<CustomObject>
    <description>Salesforce Issue fetched from the Quality Clouds API</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Documentation__c</fullName>
        <description>Documentation URL</description>
        <inlineHelpText>Documentation URL</inlineHelpText>
        <label>Documentation</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Element_Name__c</fullName>
        <description>Name of the affected element</description>
        <inlineHelpText>Name of the affected element</inlineHelpText>
        <label>Element Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact_Area__c</fullName>
        <description>Impact Area</description>
        <inlineHelpText>Impact Area</inlineHelpText>
        <label>Impact Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SCALABILITY</fullName>
                </value>
                <value>
                    <fullName>PERFORMANCE</fullName>
                </value>
                <value>
                    <fullName>MANAGEABILITY</fullName>
                </value>
                <value>
                    <fullName>SECURITY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <description>Issue Type</description>
        <inlineHelpText>Issue Type</inlineHelpText>
        <label>Issue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>Line number where the issue was detected</description>
        <inlineHelpText>Line number where the issue was detected</inlineHelpText>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Link_to_Element__c</fullName>
        <description>Go to Element</description>
        <inlineHelpText>Go to Element</inlineHelpText>
        <label>Link to Element</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Scan__c</fullName>
        <description>Scan the issue is part of</description>
        <inlineHelpText>Scan the issue is part of</inlineHelpText>
        <label>Scan</label>
        <referenceTo>Scann__c</referenceTo>
        <relationshipLabel>QCIssues</relationshipLabel>
        <relationshipName>QCIssues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Severity</description>
        <inlineHelpText>Severity</inlineHelpText>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HIGH</fullName>
                </value>
                <value>
                    <fullName>MEDIUM</fullName>
                </value>
                <value>
                    <fullName>LOW</fullName>
                </value>
                <value>
                    <fullName>WARNING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Write_Off_Request_Description__c</fullName>
        <description>Write Off Request Description</description>
        <inlineHelpText>Write Off Request Description</inlineHelpText>
        <label>Write Off Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Write_Off_Request_Reason__c</fullName>
        <label>Write Off Request Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reason1</fullName>
                    <label>Complex solution, requires refactoring</label>
                </value>
                <value>
                    <fullName>Reason2</fullName>
                    <label>Insufficient time to fix and test</label>
                </value>
                <value>
                    <fullName>Reason3</fullName>
                    <label>Complex to test and validate all situations</label>
                </value>
                <value>
                    <fullName>Reason4</fullName>
                    <label>False positive rule</label>
                </value>
                <value>
                    <fullName>Reason5</fullName>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Reason6</fullName>
                    <label>Legacy issue</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Write_off__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Write off</description>
        <inlineHelpText>Write off</inlineHelpText>
        <label>Write off</label>
        <type>Checkbox</type>
    </fields>
    <label>QCIssue</label>
    <nameField>
        <label>QCIssue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QCIssues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualityCloudsApiSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <defaultValue>&quot;https://scan.qualityclouds.com&quot;</defaultValue>
        <description>Quality Clouds API Endpoint</description>
        <inlineHelpText>Quality Clouds API Endpoint</inlineHelpText>
        <label>API Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>API_Version__c</fullName>
        <defaultValue>&quot;v2&quot;</defaultValue>
        <description>Quality Clouds API Version</description>
        <inlineHelpText>Quality Clouds API Version</inlineHelpText>
        <label>API Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_2__c</fullName>
        <label>OAuth Token 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_3__c</fullName>
        <label>OAuth Token 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_4__c</fullName>
        <label>OAuth Token 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_5__c</fullName>
        <label>OAuth Token 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token__c</fullName>
        <label>OAuth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>QualityCloudsApiSettings</label>
</CustomObject>

objects/Scann__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <description>Branch scanned. Only available for feature branch scans</description>
        <inlineHelpText>Branch scanned. Only available for feature branch scans</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Elements__c</fullName>
        <description>Number of Configuration Elements analysed</description>
        <inlineHelpText>Number of Configuration Elements analysed</inlineHelpText>
        <label>Configuration Elements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Scan date</description>
        <inlineHelpText>Scan date</inlineHelpText>
        <label>Scan Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration of the Scan</description>
        <inlineHelpText>Duration of the Scan</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Internal scan id. Used only for technical support</description>
        <externalId>true</externalId>
        <inlineHelpText>Internal scan id. Used only for technical support</inlineHelpText>
        <label>Internal ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <description>Instance for this scann</description>
        <inlineHelpText>Instance for this scann</inlineHelpText>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipName>Scanns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quality_Gate_Message__c</fullName>
        <label>Quality Gate Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quality_Gate_Result__c</fullName>
        <description>Quality Gate Result</description>
        <inlineHelpText>Quality Gate Result</inlineHelpText>
        <label>Quality Gate Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quality_of_Cloud__c</fullName>
        <description>Overall quality indicator, not available for feature branch scans</description>
        <inlineHelpText>Overall quality indicator, not available for feature branch scans</inlineHelpText>
        <label>Quality of Cloud</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scan_Type__c</fullName>
        <description>Scan Type</description>
        <inlineHelpText>Scan Type</inlineHelpText>
        <label>Scan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Result of the scan</description>
        <inlineHelpText>Result of the scan</inlineHelpText>
        <label>Scan Result</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Debt_hours__c</fullName>
        <description>Development time to fix the detected issues</description>
        <inlineHelpText>Development time to fix the detected issues</inlineHelpText>
        <label>Technical Debt (hours)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Issues__c</fullName>
        <description>Number of issues detected in the scan</description>
        <inlineHelpText>Number of issues detected in the scan</inlineHelpText>
        <label>Total Issues</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ScanDetailController.cls
public with sharing class ScanDetailController {

    private integer totalRecs = 0;
    private integer index = 0;
    private integer blockSize = 15;

    public string selectedField {get;set;}
    public string selectedDirection {get;set;}
    public string selectedImpact {get;set;}
    public string selectedSeverity {get;set;}
    public string selectedIssue {get;set;}

    public string selectedFieldFin {get;set;}
    public string selectedDirectionFin {get;set;}
    public string selectedImpactFin {get;set;}
    public string selectedSeverityFin {get;set;}
    public string selectedIssueFin {get;set;}


    private string filterWhere {get;set;}

    public String message_type_out{get;set;}
    public String message_out{get;set;}
    public String message{get;set;}
    public String message_type{get;set;}
    public String id_scan = ApexPages.currentPage().getParameters().get('id');
    public String id_instance = ApexPages.currentPage().getParameters().get('id_instance');
    Scann__c scan;
    public boolean showPopup {get;set;}
    public String reason {get;set;}
    public String description {get;set;}



    public ScanDetailController() {
        message = ApexPages.currentPage().getParameters().get('message');
        message_type = ApexPages.currentPage().getParameters().get('message_type');
        showPopup = false;
        filterWhere = '';
        selectedField = 'Issue__c';
        selectedDirection = 'ASC';
        selectedImpact = 'ALL';
        selectedSeverity = 'ALL';
        selectedIssue = '';
        selectedFieldFin = 'Issue__c';
        selectedDirectionFin = 'ASC';
        selectedImpactFin = 'ALL';
        selectedSeverityFin = 'ALL';
        selectedIssueFin = '';
        getScan();
        totalRecs = [SELECT count() FROM QCIssue__c WHERE Scan__c = :scan.id];
    }

    public String id_issue{get;set;}

    //public String issue_toupdate{get;set;}
    public String issueIdToUpdate{get;set;}
    public QCIssue__c issueToUpdate{get;set;}


    List<QCIssue__c> issues;

    public String getId_scan(){
        return id_scan;
    }
    public Scann__c getScan(){
        if (scan == null && Schema.sObjectType.Scann__c.isAccessible())
            scan = [SELECT Branch_Name__c, 
                            Date__c, 
                            Duration__c, 
                            ID__c, 
                            Instance__c, 
                            Scan_Type__c, 
                            Quality_of_Cloud__c, 
                            Configuration_Elements__c, 
                            State__c, 
                            Technical_Debt_hours__c, 
                            Total_Issues__c, 
                            Id, 
                            Quality_Gate_Result__c, 
                            Quality_Gate_Message__c
                            FROM Scann__c 
                            WHERE ID__c = :id_scan 
                            ORDER BY CreatedDate DESC];
        return scan;
    }

    public List<QCIssue__c> getIssues(){
        if (Schema.sObjectType.QCIssue__c.isAccessible()){
            totalRecs = database.countQuery('SELECT count() FROM QCIssue__c WHERE Scan__c = \'' + scan.id + '\'' + filterWhere);

            issues = database.query('SELECT Link_to_Element__c, Documentation__c, Element_Name__c, ID__c, Impact_Area__c, Issue__c, ' 
                + ' Write_off__c, Baseline__c, Line_Number__c, Severity__c, Id, Write_Off_Request_Description__c,'
                + ' Write_Off_Request_Reason__c FROM QCIssue__c WHERE Scan__c = \''
                + scan.id + '\'' + filterWhere + ' ORDER BY ' + selectedFieldFin + ' ' + selectedDirectionFin 
                + ', Baseline__c DESC LIMIT ' + blockSize + ' OFFSET ' + index);
        }
        return issues;
    }
    public PageReference go_back(){
        PageReference tempPage = new PageReference('/apex/InstanceDetail');
        tempPage.getParameters().put('id', id_instance);
        tempPage.setRedirect(true);
        return tempPage;
    }
    public PageReference openDetail(){
        PageReference tempPage = new PageReference('/apex/IssueDetail');
        tempPage.getParameters().put('id', id_issue);
        tempPage.getParameters().put('id_scan', id_scan);
        tempPage.getParameters().put('id_instance', id_instance);
        tempPage.setRedirect(true);
        return tempPage;
    }

    /* public void massiveWriteoff() {

        List<QCIssue__c> issuelisttoupdate = database.query('SELECT Id, Write_off__c FROM QCIssue__c WHERE Scan__c = \'' + scan.id + '\'' + filterWhere);

        for ( QCIssue__c issue : issuelisttoupdate) {
            issue.Write_off__c = true;
        }

        update issuelisttoupdate;

    }
    public void massiveUnWriteoff() {

        List<QCIssue__c> issuelisttoupdate = database.query('SELECT Id, Write_off__c FROM QCIssue__c WHERE Scan__c = \'' + scan.id + '\'' + filterWhere);

        for ( QCIssue__c issue : issuelisttoupdate) {
            issue.Write_off__c = false;
        }

        update issuelisttoupdate;

    }
    public void updateWriteoff() {

        QCIssue__c issuetoupdatefin = [SELECT Id, Write_off__c FROM QCIssue__c WHERE Id = :issue_toupdate];
        issuetoupdatefin.Write_off__c = ! issuetoupdatefin.Write_off__c;
        if (Schema.sObjectType.QCIssue__c.fields.Write_off__c.isUpdateable()){
            update issuetoupdatefin;
        }

    } */

    public void sortfilter() {

        selectedFieldFin = selectedField;
        selectedDirectionFin = selectedDirection;
        selectedImpactFin = selectedImpact;
        selectedSeverityFin = selectedSeverity;
        selectedIssueFin = selectedIssue;

        filterWhere = '';

        if( selectedImpactFin != 'All'){
            filterWhere += ' AND Impact_Area__c = \'' + selectedImpactFin + '\'';
        }
        if( selectedSeverityFin != 'All'){
            filterWhere += ' AND Severity__c = \'' + selectedSeverityFin + '\'';
        }
        if( selectedIssueFin != ''){
            filterWhere += ' AND Issue__c like  \'%' + selectedIssueFin + '%\'';
        }

        index = 0;

    }

    public void beginning() {

        index = 0;

    }

    public void previous() {

        index = index - blockSize;

    }

    public void next() {

        index = index + blockSize;

    }

    public void end() {

        index = totalrecs - math.mod(totalRecs,blockSize);

    }

    public boolean getprev() {
        if(index == 0)
            return true;
        else
            return false;

    }

    public boolean getnxt() {

        if((index + blockSize) > totalRecs)
        return true;
        else
        return false;

    }

    public PageReference openPopup() {
        if (showPopup) {
            return null;
        }
        issueToUpdate = new Map<Id,QCIssue__c>(issues)?.get(issueIdToUpdate);
        System.debug('issueToUpdate ' + issueToUpdate);

        if (issueToUpdate != null) {
            showPopup = true;
        }
        return null;
    }

    public PageReference cancel() {
        showPopup = false;
        return null;
    }

    public void requestWriteOff() {
        showPopup = false;

        if (issueToUpdate.Write_Off_Request_Reason__c == null && issueToUpdate.Write_off__c == true) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Please select Request Reason.' ));
            return;
        }
        try {
            HTTPResponse res  = calloutWriteOff();
            if (res.getStatusCode() == 200){
                QCIssue__c issueFromResponse = parseResponse(res.getBody());
                if (ControllerHelperQC.checkIfUserCanUpsertQCIssue()) {
                        upsert issueFromResponse ID__c;
                    } else {
                        ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Current user does not have enough permissions to create/update QCIssue__c object or its fields.'));
                    }
            } else {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, res.getBody())); 
            }       
            
        } catch (Exception e) {
            System.debug(LoggingLevel.Error, e.getStackTraceString());    
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getMessage() + ', ' + e.getCause()));
        }
    }

    private HTTPResponse calloutWriteOff(){
        Map<String, Object> attributes = new Map<String, Object>();

        if (issueToUpdate.Write_off__c == true) {
            attributes.put('write-off-status', 'REQUESTED');
            attributes.put('reason-name-id', issueToUpdate.Write_Off_Request_Reason__c);            
        } else {
            attributes.put('write-off-status', 'DECLINED');
        }
        attributes.put('description', issueToUpdate.Write_Off_Request_Description__c);
        attributes.put('developer', UserInfo.getName());

        Map<String, Object> data = new Map<String, Object>();
        data.put('id', issueToUpdate.ID__c);
        data.put('type', 'feature-branch-issue');
        data.put('attributes', attributes);

        Map<String, Object> jsonObj = new Map<String, Object>();
        jsonObj.put('data', data);

        String jsonStr = JSON.serialize(jsonObj); 

        HttpRequest req = new HttpRequest();
        QualityCloudsApiSettings__c settings = ControllerHelperQC.getSettings();
        req.setEndpoint(settings.API_Endpoint__c + '/api/'  + settings.API_Version__c + '/feature-branch-issue/' + issueToUpdate.ID__c);
        req.setMethod('PATCH');
        req.setHeader('Accept', 'application/vnd.api+json');
        req.setHeader('Content-Type', 'application/vnd.api+json');
        req.setHeader('Client-Name', 'Salesforce');
        req.setHeader('Authorization', 'Bearer '+ (settings.OAuth_token__c != null ? settings.OAuth_token__c : '') + (settings.OAuth_token_2__c != null ? settings.OAuth_token_2__c : '') + (settings.OAuth_token_3__c != null ? settings.OAuth_token_3__c : '') + (settings.OAuth_token_4__c != null ? settings.OAuth_token_4__c : '') + (settings.OAuth_token_5__c != null ? settings.OAuth_token_5__c : ''));
        req.setBody(jsonStr); 
        System.debug('request: '+ req);
        System.debug('request body: '+ req.getBody());   
        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug('response: '+ res);
        System.debug('response body: '+ res.getBody());     
        return res;
    }

    private QCIssue__c parseResponse(String res){
        Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(res);
        Map<String, Object> data = (Map<String, Object>) results.get('data');
        return ControllerHelperQC.jsonDataToIssue(data);        
    }
}