objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Featured_Banch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Featured Banch</description>
        <inlineHelpText>Is Featured Banch</inlineHelpText>
        <label>Is Featured Banch</label>
        <type>Checkbox</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QCIssue__c.object
<CustomObject>
    <description>Salesforce Issue fetched from the Quality Clouds API</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scan__c</fullName>
        <description>Scan the issue is part of</description>
        <inlineHelpText>Scan the issue is part of</inlineHelpText>
        <label>Scan</label>
        <referenceTo>Scann__c</referenceTo>
        <relationshipLabel>QCIssues</relationshipLabel>
        <relationshipName>QCIssues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Write_Off_Request_Reason__c</fullName>
        <label>Write Off Request Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reason1</fullName>
                    <label>Complex solution, requires refactoring</label>
                </value>
                <value>
                    <fullName>Reason2</fullName>
                    <label>Insufficient time to fix and test</label>
                </value>
                <value>
                    <fullName>Reason3</fullName>
                    <label>Complex to test and validate all situations</label>
                </value>
                <value>
                    <fullName>Reason4</fullName>
                    <label>False positive rule</label>
                </value>
                <value>
                    <fullName>Reason5</fullName>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Reason6</fullName>
                    <label>Legacy issue</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Write_off__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Write off</description>
        <inlineHelpText>Write off</inlineHelpText>
        <label>Write off</label>
        <type>Checkbox</type>
    </fields>
    <label>QCIssue</label>
    <nameField>
        <label>QCIssue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QCIssues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QualityCloudsApiSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <defaultValue>&quot;https://scan.qualityclouds.com&quot;</defaultValue>
        <description>Quality Clouds API Endpoint</description>
        <inlineHelpText>Quality Clouds API Endpoint</inlineHelpText>
        <label>API Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>API_Version__c</fullName>
        <defaultValue>&quot;v2&quot;</defaultValue>
        <description>Quality Clouds API Version</description>
        <inlineHelpText>Quality Clouds API Version</inlineHelpText>
        <label>API Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>QualityCloudsApiSettings</label>
</CustomObject>

objects/Scann__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <description>Branch scanned. Only available for feature branch scans</description>
        <inlineHelpText>Branch scanned. Only available for feature branch scans</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Scan date</description>
        <inlineHelpText>Scan date</inlineHelpText>
        <label>Scan Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Internal scan id. Used only for technical support</description>
        <externalId>true</externalId>
        <inlineHelpText>Internal scan id. Used only for technical support</inlineHelpText>
        <label>Internal ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <description>Instance for this scann</description>
        <inlineHelpText>Instance for this scann</inlineHelpText>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipName>Scanns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scan_Type__c</fullName>
        <description>Scan Type</description>
        <inlineHelpText>Scan Type</inlineHelpText>
        <label>Scan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Result of the scan</description>
        <inlineHelpText>Result of the scan</inlineHelpText>
        <label>Scan Result</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ScanDetailControllerTest.cls
@isTest
public class ScanDetailControllerTest {

    private class MockOK implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            if (req.getBody().contains('"write-off-status":"REQUESTED"')) {
                HTTPResponse res = new HTTPResponse();
                res.setBody('{"data":{"type":"feature-branch-issue","id":"11",'+
                '"attributes":{"scan-uuid":"6faff0ad-4ea9-4ab9-8eb4-a14ab169f46f",'+
                '"affected-element-sys-id":"https://github/17be096d/Trg_Opportunity.trigger",'+
                '"affected-element-name":"Trg_Opportunity",'+
                '"created-by":"Andrei Jicol <ajicol@qc.com>",'+
                '"created-on":"2021-03-19 10:08:00",'+
                '"updated-by":"Andrei Jicol <ajicol@qc.com>",'+
                '"updated-on":"2021-03-19 10:08:00",'+
                '"severity":"MEDIUM",'+
                '"impact-area":"MANAGEABILITY",'+
                '"issue-type":"Avoid excessive cyclomatic complexity.",'+
                '"line-number":8,'+
                '"best-practice-link":"https://docs.qualityclouds.com/CyclomaticComplexity",'+
                '"configuration-element-type":"Apex Trigger",'+
                '"reference-status":"NEW",'+
                '"write-off":{"write-off-status":"APPROVED",'+
                '"write-off-date":"2021-08-19 14:09:23",'+
                '"requested-date":"2021-08-19 14:09:23",'+
                '"request-reason":"Insufficient time to fix and test",'+
                '"request-reason-nameid":"Reason2",'+
                '"requester":"Andrei Jicol",'+
                '"validator":"Andrei Jicol",'+
                '"validation-reason":"write off descr1",'+
                '"request-description":"write off descr1",'+
                '"validation-date":"2021-08-19 14:09:23"}},'+
                '"links":{"self":"http://services-development.qualityclouds.com/api/v2/feature-branch-issue/106149"}}}');
                res.setStatusCode(200);
                return res;
            } else if (req.getBody().contains('"write-off-status":"DECLINED"')) {
                HTTPResponse res = new HTTPResponse();
                res.setBody('{"data":{"type":"feature-branch-issue",'+
                '"id":"22",'+
                '"attributes":{"scan-uuid":"6faff0ad-4ea9-4ab9-8eb4-a14ab169f46f",'+
                '"affected-element-sys-id":"https://github/17beeFirstAndLastCampaigns.trigger",'+
                '"affected-element-name":"UpdateFirstAndLastCampaigns",'+
                '"created-by":"Andrei Jicol <ajicol@qc.com>",'+
                '"created-on":"2021-03-19 10:08:00",'+
                '"updated-by":"Andrei Jicol <ajicol@qc.com>",'+
                '"updated-on":"2021-03-19 10:08:00",'+
                '"severity":"MEDIUM",'+
                '"impact-area":"MANAGEABILITY",'+
                '"issue-type":"Access permissions peration.",'+
                '"line-number":62,'+
                '"best-practice-link":"https://docs.qualityclouds.com/qcd/acon-31720331.html",'+
                '"configuration-element-type":"Apex Trigger",'+
                '"reference-status":"BASELINE",'+
                '"write-off":{"write-off-status":"DECLINED",'+
                '"write-off-date":"2021-08-19 14:07:12",'+
                '"requested-date":"2021-08-17 15:52:19",'+
                '"request-reason":"Insufficient time to fix and test",'+
                '"request-reason-nameid":"Reason2",'+
                '"requester":"ajicol@qualityclouds.com",'+
                '"validator":"Andrei Jicol",'+
                '"validation-reason":"qqqqqwww2",'+
                '"request-description":"qqqqqwww",'+
                '"validation-date":"2021-08-19 14:07:12"}},'+
                '"links":{"self":"http://services-development.qualityclouds.com/api/v2/feature-branch-issue/106174"}}}');
                res.setStatusCode(200);
                return res;
            } else {
                System.assert(false, 'unexpected request body ' + req.getBody());
                return null;
            }
        }
    }
   
    @IsTest 
    static void givenIssueWriteOffFalse_whenRequestWriteOff_thenIssueWriteOffTrue(){
        Test.setMock(HttpCalloutMock.class, new MockOK());

        Instance__c instance;
        Scann__c scan;
        QCIssue__c issueWOTrue;
        QCIssue__c issueWOFalse;
        upsert instance = new Instance__c(ID__c= '1', Is_Featured_Banch__c=true) ID__c;
        upsert scan = new Scann__c(ID__c= '123',Date__c = Datetime.valueOf('2029-07-23 08:25:59'), State__c='SUCCESS', Scan_Type__c='feature-branch-scan', Branch_Name__c='develop', Instance__c= instance.Id) ID__c;
        upsert issueWOFalse = new QCIssue__c( ID__c='11',  Write_off__c=false, Scan__c =scan.Id) ID__c;
        upsert issueWOTrue = new QCIssue__c( ID__c='22',  Write_off__c=true,  Scan__c =scan.Id) ID__c;
        upsert new QualityCloudsApiSettings__c(API_Endpoint__c = 'https://scan.qualityclouds.com', API_Version__c = 'v2' );
        
        PageReference scanDetailPage = Page.ScanDetail;
        scanDetailPage.getParameters().put('id', scan.ID__c);
        Test.setCurrentPage(scanDetailPage);

        ScanDetailController ctrl = new ScanDetailController();
        ctrl.issueIdToUpdate = issueWOFalse.ID;
        Test.startTest();
        ctrl.getIssues();
        ctrl.openPopup();
        ctrl.issueToUpdate.Write_Off_Request_Reason__c = 'Reason1';
        ctrl.issueToUpdate.Write_off__c = true;
        ctrl.requestWriteOff();
        Test.stopTest();

        Boolean actualWriteOffStatus = [SELECT Write_off__c, ID__c FROM QCIssue__c WHERE ID__c =:issueWOFalse.ID__c ].Write_off__c;
        System.assertEquals(true, actualWriteOffStatus);
    }

    @IsTest 
    static void givenIssueWriteOffTrue_whenRequestWriteOff_thenIssueWriteOffFalse(){
        Test.setMock(HttpCalloutMock.class, new MockOK());

        Instance__c instance;
        Scann__c scan;
        QCIssue__c issueWOTrue;
        QCIssue__c issueWOFalse;
        upsert instance = new Instance__c(ID__c= '1', Is_Featured_Banch__c=true) ID__c;
        upsert scan = new Scann__c(ID__c= '123',Date__c = Datetime.valueOf('2029-07-23 08:25:59'), State__c='SUCCESS', Scan_Type__c='feature-branch-scan', Branch_Name__c='develop', Instance__c= instance.Id) ID__c;
        upsert issueWOFalse = new QCIssue__c( ID__c='11',  Write_off__c=false, Scan__c =scan.Id) ID__c;
        upsert issueWOTrue = new QCIssue__c( ID__c='22',  Write_off__c=true,  Scan__c =scan.Id) ID__c;
        upsert new QualityCloudsApiSettings__c(API_Endpoint__c = 'https://scan.qualityclouds.com', API_Version__c = 'v2' );
        
        PageReference scanDetailPage = Page.ScanDetail;
        scanDetailPage.getParameters().put('id', scan.ID__c);
        Test.setCurrentPage(scanDetailPage);

        ScanDetailController ctrl = new ScanDetailController();
        ctrl.showPopup = false;
        ctrl.issueIdToUpdate = issueWOTrue.ID;
        Test.startTest();
        ctrl.getIssues();
        ctrl.openPopup();
        ctrl.issueToUpdate.Write_Off_Request_Reason__c = 'Reason1';
        ctrl.issueToUpdate.Write_off__c = false;
        ctrl.requestWriteOff();
        Test.stopTest();

        Boolean actualWriteOffStatus = [SELECT Write_off__c, ID__c FROM QCIssue__c WHERE ID__c =:issueWOTrue.ID__c ].Write_off__c;
        System.assertEquals(false, actualWriteOffStatus);
    }
}