objects/Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QualityCloudsApiSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <defaultValue>&quot;https://scan.qualityclouds.com&quot;</defaultValue>
        <description>Quality Clouds API Endpoint</description>
        <inlineHelpText>Quality Clouds API Endpoint</inlineHelpText>
        <label>API Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>API_Version__c</fullName>
        <defaultValue>&quot;v2&quot;</defaultValue>
        <description>Quality Clouds API Version</description>
        <inlineHelpText>Quality Clouds API Version</inlineHelpText>
        <label>API Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_2__c</fullName>
        <label>OAuth Token 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_3__c</fullName>
        <label>OAuth Token 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_4__c</fullName>
        <label>OAuth Token 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token_5__c</fullName>
        <label>OAuth Token 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_token__c</fullName>
        <label>OAuth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>QualityCloudsApiSettings</label>
</CustomObject>

objects/Scann__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <description>Branch scanned. Only available for feature branch scans</description>
        <inlineHelpText>Branch scanned. Only available for feature branch scans</inlineHelpText>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Scan date</description>
        <inlineHelpText>Scan date</inlineHelpText>
        <label>Scan Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Internal scan id. Used only for technical support</description>
        <externalId>true</externalId>
        <inlineHelpText>Internal scan id. Used only for technical support</inlineHelpText>
        <label>Internal ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <description>Instance for this scann</description>
        <inlineHelpText>Instance for this scann</inlineHelpText>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipName>Scanns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scan_Type__c</fullName>
        <description>Scan Type</description>
        <inlineHelpText>Scan Type</inlineHelpText>
        <label>Scan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Result of the scan</description>
        <inlineHelpText>Result of the scan</inlineHelpText>
        <label>Scan Result</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/globalCallsToQC.cls
/**
 * @description Class where we Execute the Scan
 */
global with sharing class globalCallsToQC {
    global globalCallsToQC() {

    } 

    /**
     * @description Deprecated method whitout the Manual variable
     */
    global boolean execute_scann(Instance__c instance, String gitBranch ){
       return null;
    }

    /**
     * @description New method whit the Manual variable
     */
    global boolean execute_scann(Instance__c instance, String gitBranch, Boolean manual){
      
        HttpRequest req = new HttpRequest();
        QualityCloudsApiSettings__c settings = ControllerHelperQC.getSettings();

        req.setEndpoint(settings.API_Endpoint__c + '/api/'  + settings.API_Version__c + '/feature-branch-scan');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/vnd.api+json');
        req.setHeader('Accept', '*/*');
        req.setHeader('client-name', 'GenericHttpClient');
        req.setHeader('Authorization', 'Bearer '+ (settings.OAuth_token__c != null ? settings.OAuth_token__c : '') + (settings.OAuth_token_2__c != null ? settings.OAuth_token_2__c : '') + (settings.OAuth_token_3__c != null ? settings.OAuth_token_3__c : '') + (settings.OAuth_token_4__c != null ? settings.OAuth_token_4__c : '') + (settings.OAuth_token_5__c != null ? settings.OAuth_token_5__c : ''));
        
        //If manual is diferent than null send it in the body
        if(manual != null){
            req.setBody('{"data": {"type": "feature-branch-scan","attributes": {"url-id": ' + instance.ID__c + ',"scan-type": 5,"feature-branch": "' + gitBranch + '", "manual": ' + manual + '}}}');
        }else{
            req.setBody('{"data": {"type": "feature-branch-scan","attributes": {"url-id": ' + instance.ID__c + ',"scan-type": 5,"feature-branch": "' + gitBranch + '" }}}');
        }
        req.setTimeout(120000);
        Http http = new Http();
        HTTPResponse res = http.send(req);

        if (res.getStatusCode() == 202){
            jsontoscan.Jsontoscan_c result =  jsontoscan.Jsontoscan_c.parse(res.getBody());
            String txt_date = result.data.attributes.scan_date.replace('T', ' ');
            txt_date = txt_date.substring(0, 19);
            Datetime scan_date = Datetime.valueOf(txt_date);
			if (Schema.sObjectType.Scann__c.isCreateable()){
               insert new Scann__c(Date__c = scan_date, State__c = result.data.attributes.status, ID__c = result.data.id, Scan_Type__c = result.data.type_Z, Branch_Name__c = gitBranch, Instance__c = instance.Id) ;
                return true;
            }else {
                throw new ControllerHelperQC.NoPermissionException('Current user does not have enough permissions to create Scann__c object.');
            }

        }
        return false;
    }

    /**
     * @description Update scan method
     */
     global boolean update_scanns(){        
        return true;
    }
}